// <auto-generated />
using APISimples.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace APISimples.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    partial class DataBaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("APISimples.Models.ConversaModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("idUser1")
                        .HasColumnType("integer");

                    b.Property<int>("idUser2")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("idUser1");

                    b.HasIndex("idUser2");

                    b.ToTable("Conversas");
                });

            modelBuilder.Entity("APISimples.Models.MensagemModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("conteudo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("conversaId")
                        .HasColumnType("integer");

                    b.Property<int>("remetenteId")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("conversaId");

                    b.HasIndex("remetenteId");

                    b.ToTable("Mensagens");
                });

            modelBuilder.Entity("APISimples.Models.UsuarioModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("APISimples.Models.ConversaModel", b =>
                {
                    b.HasOne("APISimples.Models.UsuarioModel", "user1")
                        .WithMany("conversasIniciadas")
                        .HasForeignKey("idUser1")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APISimples.Models.UsuarioModel", "user2")
                        .WithMany("conversasParticipadas")
                        .HasForeignKey("idUser2")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("user1");

                    b.Navigation("user2");
                });

            modelBuilder.Entity("APISimples.Models.MensagemModel", b =>
                {
                    b.HasOne("APISimples.Models.ConversaModel", "conversa")
                        .WithMany("mensagens")
                        .HasForeignKey("conversaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APISimples.Models.UsuarioModel", "remetente")
                        .WithMany()
                        .HasForeignKey("remetenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("conversa");

                    b.Navigation("remetente");
                });

            modelBuilder.Entity("APISimples.Models.ConversaModel", b =>
                {
                    b.Navigation("mensagens");
                });

            modelBuilder.Entity("APISimples.Models.UsuarioModel", b =>
                {
                    b.Navigation("conversasIniciadas");

                    b.Navigation("conversasParticipadas");
                });
#pragma warning restore 612, 618
        }
    }
}
